select 
	(select nombre from contabilidad.tipo_comprobante where id=l.id_tipo_comprobante) as nombre_tipo_comprobante,
	(select nombre_completo from cartera.cliente where id=l.id_cliente) as nombre_completo_cliente,
	l.ruc as ruc_dato,
	l.numero_documento,
	l.fecha_emision,
	l.fecha_registro_contable,
	l.numero_serie,
	l.numero_autorizacion,
	l.bienes_iva,
	l.servicion_iva,
	l.total_iva,
	l.bienes_sin_iva,
	l.servicios_sin_iva,
	l.total_sin_iva,
	(select id from contabilidad.tipo_iva where id=l.id_tipo_iva) as id_tipo_iva,
	l.monto_iva,
	l.monto_ice,
	l.transfe_iva_retener,
	(select id from contabilidad.tipo_retencion_iva where id=l.id_tipo_retencion_iva) as id_tipo_retencion_iva,
	l.transfe_iva_retenido,
	l.presta_iva_retener,
	(select id from contabilidad.tipo_retencion_iva where id=l.id_tipo_retencion_iva_presta) as id_tipo_retencion_iva_presta,
	l.presta_iva_retenido,
	l.fecha_caducidad,
	(select codigo from contabilidad.asiento_contable where id=l.id_asiento_contable) as codigo_asiento_contable,
	l.numero_documento_contable
from sris.transaccion_local l inner join cartera.cliente c on l.id_cliente=c.id
--where